### ISSUE TITLE
Affine transformation in processing profile faces may cause large distortions

### ISSUE THREAD

**Issue by ywu36** [cmusatyalab/openface#113]
### Context of the issue.
We try to use the Openface to compute the similarity between two profile faces, and we found that the aligned image are heavily distorted due to the small distances between eyes. Since the Dlib face detector   failed to work, we input our manually annotated landmarks for alignment.

### Expected behavior.
1. Could we bypass the alignment step and just feed the original image as the input of the deep network ? Will the result meaningful ?
2. How did the algorithm handle the large pose problem in training, in LFW, we have some images with large pose, did we using the same 'affine transformation' in training ?

**Comment by bamos** [comment]
Hi @ywu36 - we haven't explored profile faces and I'm not sure if the results of not using alignment will be meaningful. On your second question, all of the training and LFW testing was done with nearly frontal faces that the affine transformation works well on.

I'm closing this issue since we don't have any development plans to address profile faces, but I'd be happy to hear from you with any interesting results on this.

-Brandon.
