### ISSUE TITLE
net.forward value different between ubuntu(x64,x86) and Android(arm 32).

### ISSUE THREAD

**Issue by Vincechen611** [cmusatyalab/openface#115]
We try to use torch-Android to load Openface nn4.small2.v1.t7 (apkbinary64 from torch android) to get the net.forward value on android, but the result of net:forward function is different with Ubuntu. We are sure that the torch package on android is same as the package on Ubuntu.
We compare 128 features  from ubuntu and 128 features from android with same 96*96 image,  the distance is very large about 1.31... .
Call you give us same suggest ?

This [attachment](https://drive.google.com/file/d/0B3K2J-Bb0QjEeGk2Uk9ucEtHUVE/view?usp=sharing
) content the 128 features from ubuntu (x64,x86) and android(arm 32)

+ Operating system: ubuntu(14.04 64bit & 14.04 32bit) , Android( 5.1.1 up)
+ Torch version: Torch7
+ CPU architecture: x64, x86 ,arm32
+ GPU type (if using): NVIDIA GeForce GTX 860M 4G-DDR5

**Comment by bamos** [comment]
Hi @Vincechen611 - I'm not sure how to debug this. Since the OpenFace Torch model is almost standalone, maybe somebody from the Torch community will be able to help? Their mailing list is at https://groups.google.com/forum/#!forum/torch7.

Send them a link to the model binary and a code snippet that looks like the following but gives different results between CPU and Android:

```Th
net = torch.load(<openface-model>)
net:forward(torch.ones(1, 3, 96, 96))
```

I'm keeping this issue open for now in case there's an OpenFace change we can make to fix this.

-Brandon.

**Comment by Vincechen611** [comment]
Hi @bamos We find that the error is caused by our mistake.
We try to pass the image data from c to lua Instead of loading image file with torch image.load function, but we forgot to transform RGB value to byte for the FloatTensor...
Sorry for the trouble...

-Vince

**Comment by bamos** [comment]
Hi Vince, glad you were able to resolve this!

-Brandon.
