### ISSUE TITLE
Triple Sampling Strategy

### ISSUE THREAD

**Issue by aaronnech** [cmusatyalab/openface#139]
Hi! I'm wondering if the triple sampling strategy employed by FaceNet is different than OpenFace, and if so, why the current strategy was chosen. From reading, I've gathered the following (correct me if I'm wrong):

**FaceNet does the following:**

- Sample a minibatch, at random (they don't specify number of identities, but say 40 faces per identity).
- **Sprinkle in some additional randomly sampled negatives not from the minibatch**
- Find all anchor-positive pairs in the minibatch
- For each pair select the **closest** negative to the anchor in the minibatch which is **further** than the positive of the pair. (These negative will lie within the alpha margin 0.2)
- They found picking negatives much closer than the positive ends up collapsing training
- Optimize over these triples.

**Openface does the following:**

https://github.com/cmusatyalab/openface/blob/master/training/train.lua#L144

- Sample a minibatch at random
- Find all anchor-positive pairs
- For each pair, **find all negatives in the minibatch within the margin (alpha = 0.2)**. Further away negatives are ignored due to the collapsing training described above.
- **Randomly choose a negative** from the set above.
- Optimize over these triples.

I bolded what I think are key differences. I think these differences will have small impact on accuracy for small datasets (where the set of all triples T is not huge). But for bigger datasets the set of all possible triples, T, is giant, so proper triple selection seems much more crucial.

Was any experimentation done in this area?

Thanks!

**Comment by bamos** [comment]
Hi, this mailing list has a related discussion on training, though it doesn't exactly discuss these topics: https://groups.google.com/d/topic/cmu-openface/dcPh883T1rk/discussion

+ I don't remember why we're just randomly sampling within the margin instead of selecting a semi-hard negative. Do you remember @melgor?
+ I haven't tried adding random negatives not in the minibatch.

I'd be interested in being more consistent with the FaceNet training procedure. If you're interested,
can you add these changes in a fork? I can try training a new model with them on my dataset.

-Brandon.

**Comment by melgor** [comment]
Hi, so for Triplet Sampling we just use the [VGG-Face](http://www.robots.ox.ac.uk/~vgg/software/vgg_face/) strategy. They, as you write, choose random negative example within the margin.
The main issue of FaceNet Triplet Sampling strategy was trouble of finding such negative example which satisfy the condition (further away that positive sample), I think this was because of smaller batch size (~300 compared to 1800, and FaceNet have 45 identities with 40 images each). This slow down training a lot. The first version of OpenFace have FaceNet sampling strategy. Theoretically, we could allow user to choose between both of them.

> They found picking negatives much closer than the positive ends up collapsing training

As I remember, they found choosing hard-negative examples to collapse the training. But VGG use some kind of semi-hard negative, as sometimes we have very hard example (really close to anchor) and sometimes easier (further away than positive).

About sampling random negatives, we do not try it. But I do not think it will boost performance a lot.
