### ISSUE TITLE
Speeding torch for Mac machines

### ISSUE THREAD

**Issue by markroxor** [cmusatyalab/openface#175]
### Context of the issue.
While going through the repo I noticed that while addressing the issue in Torch at [#691](https://github.com/torch/torch7/issues/691) for Ubuntu the number of threads used is set to 1 at [#L30](https://github.com/cmusatyalab/openface/blob/master/openface/openface_server.lua#L30) for all OS. But this workaround reduces performance on Mac based machines which can otherwise be better [because it doesn't have OpenMP](https://github.com/torch/torch7/issues/691#issuecomment-222001489).

### Expected behavior.
NA

### Actual behavior.
NA

### Steps to reproduce.
NA

### OS and hardware information.
NA

**Comment by markroxor** [comment]
Can we first find the OS on which the script is executed beforehand in the LUA script itself and choose whether to or not to set number of threads used to "1"?  @bamos I might have missed something. If not should I send a PR? Advice.

**Comment by bamos** [comment]
+ [Mailing list discussion on why this was set](https://groups.google.com/forum/#!topic/cmu-openface/vqkkDlbfWZw)

---

Can you send some performance numbers of `torch.setnumthreads` for different numbers of threads with our `util/profile-pipeline.py` script on your machine? What OS are you using? Do you have OpenMP installed?

Are you saying that setting `torch.setnumthreads` to something greater than 1 on Mac, without OpenMP, increases performance? Looking at [the source](https://github.com/torch/torch7/blob/eb8d7f2752f2b714135b862d148600c60329ac26/utils.c#L172) for `torch.setnumthreads`, this function doesn't do anything if the compiler isn't using OpenMP.

```Lua
static int torch_setnumthreads(lua_State *L)
{
#ifdef _OPENMP
  int nth = luaL_checkint(L,1);
  omp_set_num_threads(nth);
#endif
  return 0;
```

**Comment by markroxor** [comment]
I did not go through [the source](https://github.com/torch/torch7/blob/eb8d7f2752f2b714135b862d148600c60329ac26/utils.c#L172) before but now it really looks like without OpenMP installed it doesn't do anything but now can't relate why we have better results on Mac. Maybe his Ubuntu and Mac machines had different specifications. 

Anyways the performance numbers:
with 1 thread-
```shell
Argument parsing and loading libraries took 0.2003 seconds.
Loading the dlib and OpenFace models took 1.4579 seconds.
Image size: (128, 134, 3)
Number of iterations: 100
Average Detection Time (seconds): 0.0330 +/- 0.0010
Average Alignment Time (seconds): 0.0049 +/- 0.0002
Average Neural Net Representation Time (seconds): 0.0755 +/- 0.0120
Average Total Time (seconds): 0.1133 +/- 0.0114
```

with 2 threads-
```shell
Argument parsing and loading libraries took 0.2017 seconds.
Loading the dlib and OpenFace models took 1.4532 seconds.
Image size: (128, 134, 3)
Number of iterations: 100
Average Detection Time (seconds): 0.0331 +/- 0.0022
Average Alignment Time (seconds): 0.0049 +/- 0.0007
Average Neural Net Representation Time (seconds): 0.0759 +/- 0.0145
Average Total Time (seconds): 0.1139 +/- 0.0144
```

with 4 threads-
```shell
Argument parsing and loading libraries took 0.1891 seconds.
Loading the dlib and OpenFace models took 1.4747 seconds.
Image size: (128, 134, 3)
Number of iterations: 100
Average Detection Time (seconds): 0.0327 +/- 0.0010
Average Alignment Time (seconds): 0.0049 +/- 0.0001
Average Neural Net Representation Time (seconds): 0.0738 +/- 0.0100
Average Total Time (seconds): 0.1114 +/- 0.0095
```

OS - Linux Mint 18 Cinnamon 64-bit

The gcc/g++ version I am using is 5.4.0 which has openMP support.

**Comment by bamos** [comment]
Since the timing differences on the representation time are negligible, let's just stay with 1 thread since in some cases (like the mailing list thread I linked), having multiple threads really hurts performance. If anybody has another case where using multiple threads is really helpful, let us know and we can try to come up with an automatic way to change this.

**Comment by hexerei** [comment]
@bamos are you suggesting, that we should make performance tests with different **OS**s and settings to compare the impact? I am using Mac newest OS X, Ubuntu 14.04, Mint 18, kubuntu, ArchLinux and Windows10. Therefore I could do some comparing, only, how important is that at this stage, since even on Mac I am working on Ubuntu because of compatibility. I do desire a pure Mac solution, but I don't see the priority right now. Still I am more than willing to contribute with performance tests to gather a prospect overview of performance issues and possible solutions.

**Comment by bamos** [comment]
Hi @hexerei - I think the issue is using OpenMP vs not using OpenMP, which happens to sometimes be correlated with the operating system. When using OpenMP, my intuition is that the number of threads should be set to one because of the small data sizes. When not using OpenMP, it doesn't matter because `torch.setnumthreads` doesn't do anything. If you're using OpenMP on any of your systems, you can try changing `torch.setnumthreads` to verify that just having one thread is optimal. You can profile the runtime with `./util/profile-pipeline.py`

**Comment by hexerei** [comment]
Great! I will give that a try (unfortunately in September since I am blocked) and return with Feedback.
