### ISSUE TITLE
saving faces after learning

### ISSUE THREAD

**Issue by volkovmqx** [cmusatyalab/openface#19]
Hello,
I don't know if this is an issue or a non developed option. i am trying to recognize faces, but when i did make the learn process, and refrech the page, all data get lost. 
Thanks

**Comment by bamos** [comment]
Hi @volkovmqx - great idea here, it's currently not developed. I just added a slight clarification to the README.

Would you find a button that will allow you to download a model compatible with the 
"training a classifier" demo (https://github.com/cmusatyalab/openface#demo-3-training-a-classifier) useful?

Or are you more interested in exporting the entire browser state with the images and classifier so that they can be imported again in the future?

-Brandon.

**Comment by volkovmqx** [comment]
well, maybe this idea a little bit better: 
in addition of the export /import feature, use cookies to import automatically the classifier upon page load, because it makes no sense that when you open the page, you need to import every time.
Thanks.

**Comment by bamos** [comment]
Yeah, I like the cookie idea too. Filing with `help wanted` for now since this isn't on our critical path.

**Comment by askz** [comment]
Hi ! is there any news on this ?

**Comment by bamos** [comment]
Hi @askz - I haven't further looked into this. Are you interested in helping?

-Brandon.

**Comment by askz** [comment]
Hi @bamos, I'm really interested in helping, the project isn't finished at all and has really good potential.
I know more systems than programming but I know python and other langs. Which DB would be appropriate for this kind of application? I have no Idea..

**Comment by bamos** [comment]
Hi Max - great! This is pretty open-ended, but I think the cleanest way to do this would be:

1. Add a way to the website for users to save, view, load, delete, and retrieve on-disk state by adding new commands to the WebSocket protocol. For example, I could click a **save** button, type in a tag like `Brandon-2015-01-15`. Then a list showing the available state would show `Brandon-2015-01-05`, and I could then choose to delete, load, or retrieve it. Retrieving it would return a file that's compatible with the classification demo.
To simplify the development on this part, don't worry about actually saving the data, just write out blank files to disk to simulate it.

2. Write Python code to load and save the server's state to disk. Instead of using a database, I think it's valuable to use the same serialization as the classification demo. This way users can download the models and use it in other code. The web demo needs other state (like the images) as well.

Let me know if I can clarify anything and I'm happy to review your commits if you start implementing this. Fork our project, develop in a separate branch, like `askz/demo-serialization`, then send in a pull request mentioning this issue where we can further discuss the changes.

-Brandon
