### ISSUE TITLE
Not closing luajit processes

### ISSUE THREAD

**Issue by danielperezr88** [cmusatyalab/openface#194]
### Context of the issue.

I'm trying to build an age/gender recognition API service.
### Expected behavior.

Close children luajit processes once used.
### Actual behavior.

When I put it to work, it leaves an open luajit process for every request received. In a couple of minutes, RAM is full and machine goes down. I use "TorchNeuralNet" class and the "forward" method just as in the "classifier.py" demo. I tried explicitly destructing "TorchNeuralNet" instance before using it, but it didn't work.
### Steps to reproduce.

It should be reproductible with a closed loop python process in which "forward" method from "TorchNeuralNet" is used.
### OS and hardware information.
- Operating system: Ubuntu 14.04 (bamos/openface docker image)
- Torch version: same as in bamos/openface docker image
- CPU architecture: x64 (GCE machine)
- GPU type (if using): None

**Comment by bamos** [comment]
Hi, do I understand correctly that you creating a new `TorchNeuralNet` object for every request? I recommend using just a single one if possible because otherwise loading the Lua subprocess adds unnecessary delay to the processing time. However it also makes sense to add a destructor that kills off the subprocess like in the exit handler. I'll merge a PR if anybody adds this.

-Brandon.

**Comment by danielperezr88** [comment]
Thanyou! That's a good point! I don't know how I didn't realize this could be fixed reusing the same instance. I would help on the destructor implementation if I felt confident enough with python-lua interfacing, but I'm afraid I don't have a clue...

Thanks again!

**Comment by bamos** [comment]
Hi, I just added a destructor that I think will now correctly kill off the subprocess when the object is destroyed. Can you check out the latest master branch and see if it works for you?

**Comment by danielperezr88** [comment]
Perfect! I'll try and save 10 minutes in the next few days to run a test.

**Comment by Alexx-G** [comment]
@bamos Destructor doesn't work for me at all, because it's not reliable for resource management.
In my case it's necessary to create a TorchNeuralNet object per task (to preserve scalability and have Torch subprocess only when it's needed). And because destructor doesn't have deterministic behavior, I ended up with zombie processes several times.
I've created a pull request #223 which allows to use TorchNeuralNet object as context manager and explicitly kill the subprocess.
Can you review it?

**Comment by vlog-yamamoto** [comment]
TorchNeuralNet class creates a zombie process and does not close the pipe.
An error occurred when executing the following code

```
while True:
  with TorchNeuralNet(model=model) as net:
      net.forwardPath(pathToTheFile)
```

error
```
    r, w = os.pipe()
OSError: [Errno 24] Too many open files
```

```
ps ax

17676 s002  Z+     0:00.00 (luajit)
17686 s002  Z+     0:00.00 (luajit)
```

It will execute self.p.kill () with the `__exit__` function etc, but I think that it is caused by not executing os.waitpid and pipe close.
os.waitpid and pipe close are executed by Popen.communicate.
I think that it is better to execute p.communicate () after p.kill () like https://github.com/cmusatyalab/openface/blob/master/openface/torch_neural_net.py#L171
