### ISSUE TITLE
Pre-trained Model download cannot finish.   Pandas cannot import.

### ISSUE THREAD

**Issue by carol007** [cmusatyalab/openface#196]
### Context of the issue.
I almost finish the setup and run the final step :    `models/get-models.sh `
dlib models downloaded but NN model cannot. the terminal has no command line return back.
I tried to kill the terminal and run demos, but all of them return various error, such as "no module named Pandas", "Cannot find this file or directory". When I  check back the python package and try pip install pandas again and again but still return as followed:
    ----------------------------------------
Cleaning up...
**Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/pandas/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-cCqvrj-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/pandas
Storing debug log for failure in /root/.pip/pip.log**

How can I successfully run the demo?

**Comment by bamos** [comment]
Hi @carol007 - these manual installation issues can be tricky to debug and I haven't seen the error that you're getting before. To work around installation issues, I recommend trying out our Docker build as described in our [setup guide](http://cmusatyalab.github.io/openface/setup/). I'm closing this issue for now because it's not directly related to OpenFace.

-Brandon.
