### ISSUE TITLE
Please explain the structure of the raw-data directory

### ISSUE THREAD

**Issue by kaikuehne** [cmusatyalab/openface#22]
Hi,
this is not a real issue but rather a question.
Maybe I have not seen this or am a bit overwhelmed because this is all new to me,
but can you explain how the images should be structured when training a new classifier?
So, when calling ./util/align-dlib.py <path-to-raw-data> which structure must the raw-data directory have?
Do I need to create a folder for each person with N photos, where the folder name is later used
as a label?

Thanks

**Comment by bamos** [comment]
Hi @kaikuehne - does the following section I just added help?

---

1. Create a directory for your raw images so that images from different
   people are in different subdirectories. The names of the labels or
   images do not matter, and each person can have a different amount of images.
   The images should be formatted as `jpg` or `png` and have
   a lowercase extension.

   ```
   $ tree data/mydataset/raw
   person-1
   ├── image-1.jpg
   ├── image-2.png
   ...
   └── image-p.png

   ...

   person-m
   ├── image-1.png
   ├── image-2.jpg
   ...
   └── image-q.png
   ```

**Comment by kaikuehne** [comment]
Hi @bamos,
I think I got it working, thanks for adding the explanation.
I didn't want to create a new model tough but rather just create
a new classifier based on the model (using classifier.py), as
you described in issue #23.
