### ISSUE TITLE
running openface on a large dataset >1000 image

### ISSUE THREAD

**Issue by boulabiar** [cmusatyalab/openface#268]
### Context of the issue.
Many images in the DB.

### Expected behavior.
Having linear performance instead of exponential.

### Actual behavior.
after adding many pictures to the database, performance becomes low.
This is what I get in the SVM training step.

16 faces : 0.15s
226 faces : 2.8s
550 faces : 40 to 50s
1500 faces : ??

### Steps to reproduce.
just add about 1000 face to the database

**Comment by bamos** [comment]
You can try using a different classifier.

**Comment by boulabiar** [comment]
Sorry for bugging, what do you suggest to be used while still giving good results? Thanks

**Comment by bamos** [comment]
A neural network with a single hidden layer should scale better.

**Comment by decoded4620** [comment]
@bamos It will only scale slightly better. Facial Recognition Data Convergence on any number of hidden layers is simply not linear.  The only way to get better performance is with some form of `map-reduce` to train the layers where parallel operations can be achieved. This is why frameworks like CUDA are farming all of the AI training to the GPU clusters (there can be literally thousands of GPU's on a VC), rather than your dinky little 4 core processor :-1:

**Comment by MLDSBigGuy** [comment]
Try kdtrees of knn classifier
