### ISSUE TITLE
minimal working example for training failing

### ISSUE THREAD

**Issue by ashwinnair14** [cmusatyalab/openface#274]
### Context of the issue.
Hello,
I was trying to run the train example using the Minimal Working Example to Extract Features as input.

### Expected behavior.
Ideally, it should train and save the pkl file.

### Actual behavior.
```
Traceback (most recent call last):
  File "demos/classifier.py", line 296, in <module>
    train(args)
  File "demos/classifier.py", line 116, in train
    le = LabelEncoder().fit(labels)
  File "/home/anilil/anaconda3/envs/tensorflow/lib/python3.5/site-packages/sklearn/preprocessing/label.py", line 112, in fit
    y = column_or_1d(y, warn=True)
  File "/home/anilil/anaconda3/envs/tensorflow/lib/python3.5/site-packages/sklearn/utils/validation.py", line 562, in column_or_1d
    raise ValueError("bad input shape {0}".format(shape))
ValueError: bad input shape ()

```

### Steps to reproduce.
```
mkdir -p classify-test/raw/{lennon,clapton}
cp images/examples/lennon-* classify-test/raw/lennon
cp images/examples/clapton-* classify-test/raw/clapton
./util/align-dlib.py classify-test/raw align outerEyesAndNose classify-test/aligned --size 96
./batch-represent/main.lua -outDir classify-test/features -data classify-test/aligned

./demos/classifier.py train classify-test/features

```
### OS and hardware information.

+ Operating system: [Ubuntu 16.04]
+ Torch version: [0.9]
+ CPU architecture: [x64]
+ GPU type (if using): [GTX 1080]

**Comment by natuschen** [comment]
Hello. 
I met the same problems as u posted above, where my env is [a redhat-like enterprise linux kernel, python3.6.2, torch 7, x86_64 architecture]. 
i wonder if u notice that the variable 'shape' cannot be formatted automatically by python executor. it made me quite confused so that i dived into the file './demos/classifier.py', then i found that the code is not completely compatible with python 3.
for example, at file './demos/classifier.py' function ''train"  line 107, function 'map()' would return a map object rather than a list object (as what would be returned to the invoker in python 2.x) . Another problem are at file './demos/classifier.py' function ''infer"  line 201.
With the aforementioned incompatibility problems fixed, my training process passed.

**Comment by shivani-vemula** [comment]
@natuschen 
can you say how you have fixed those incompatibility problems

**Comment by natuschen** [comment]
**In file  './demos/classifier.py'
***line 107~109
labels = list(map(itemgetter(1),
                 map(os.path.split,
                     map(os.path.dirname, labels))))  # Get the directory.
***around line 201
   variable 'person' cannot be decoded, just remove it
