### ISSUE TITLE
Docker automated build?

### ISSUE THREAD

**Issue by hbredin** [cmusatyalab/openface#35]
For some reason, building the docker image is failing on my Mac.
To make things even easier, did you consider setting up a Docker-Hub automated build?
https://docs.docker.com/docker-hub/builds/

With this in place, running openface would be just a matter of 
```
$ docker pull openface/openface 
$ docker run openface/openface ...
```

This would also ensure that the Docker image is always up-to-date with the latest GitHub commit.

**Comment by bamos** [comment]
Thanks, we'll add a Docker automated build.

Interesting your Docker image is failing to build on your Mac.
Can you send any debug information or messages you're getting?

-Brandon.

**Comment by bamos** [comment]
Building the Docker image from scratch on my Mac still works, interested to see why yours isn't.

**Comment by onurays** [comment]
@bamos Could you please share step by step setup instructions which you follow? Me and my other 3 friends are also unable to setup & run demo on Mac.

**Comment by bamos** [comment]
Hi, have you all tried using docker? I included every command in the
Dockerfile to setup on an unmodified Ubuntu machine.

**Comment by hbredin** [comment]
I just tried building the docker image again on my mac. It works -- don't know what happened the first time I tried. Thanks.

**Comment by bamos** [comment]
Thanks again for the reference @hbredin. I set up a Docker automated build at https://hub.docker.com/r/bamos/openface/ and it's working well. Pull this is much faster than building the container.

-Brandon.

**Comment by bamos** [comment]
The docker automated build started timing out and failing because the OpenFace Docker image takes a few hours to build.
I could have switched OpenFace to a Docker repository and manually built and pushed instead of automated build, but I like having the automated build so people can get the latest version of the dependencies and code.

To significantly reduce the build times, I've created a Docker repository at https://hub.docker.com/r/bamos/ubuntu-opencv-dlib-torch/ that contains a versioned image of OpenCV, dlib, and Torch that the main OpenFace dockerfile is based on. I build and version this locally so it also won't have Docker automated build timeout issues.

The `FROM` part of the Dockerfile is not pretty,
but I think the versioning information is important:

```
FROM bamos/ubuntu-opencv-dlib-torch:ubuntu_14.04-opencv_2.4.11-dlib_18.16-torch_2015.01.12
```

After 5 days of failed builds, the automated build is successfully working again!

![2016-01-12-165130_825x1039_scrot](https://cloud.githubusercontent.com/assets/707462/12278051/d0604394-b94c-11e5-846e-b223121480a3.png)

**Comment by chalene** [comment]
Hi @bamos , you said
`The FROM part of the Dockerfile is not pretty,
but I think the versioning information is important:

FROM bamos/ubuntu-opencv-dlib-torch:ubuntu_14.04-opencv_2.4.11-dlib_18.16-torch_2015.01.12`

Do you mean the version of Dockerfile is different from the one in [your github ](https://github.com/cmusatyalab/openface/blob/master/opencv-dlib-torch.Dockerfile)or depended on what? My ubuntu version or the latest version of dependencies and code?

I have tried with the instruction on [ your FAQ](http://cmusatyalab.github.io/openface/faq/#im-getting-an-illegal-instruction-error-in-the-pre-built-docker-container) but not sure which version I should use to build on opencv-dlib-torch Dockerfile and Dockerfile

PS: I am using ubuntu 15.10, Torch 7. I am stuck with Illegal instruction (core dumped) which drives me crazy. Please help me. Thanks.
