### ISSUE TITLE
Got a problem with docker

### ISSUE THREAD

**Issue by AlvaroN1997** [cmusatyalab/openface#383]
So, i want to build a docker container locally, the problem is when i use this command

`docker build -t openface .`

It shows me the following error:

`unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /root/Dockerfile: no such file or directory`

Someone knows how to fix it?

**Comment by thayannevls** [comment]
Hi @AlvaroN1997 

You need to run `docker build -t openface .` from **openface** directory. This error is because Docker can't find a Dockerfile in the current folder. So, you just have to clone this repository and run this command.

After you do this, don't forget to run 
`docker run -p 9000:9000 -p 8000:8000 -t -i openface /bin/bash`

If you have any further questions, don't be afraid to ask!

**Comment by omerasif-itu** [comment]
> `docker build -t openface .`

ends up looking like this in my case:

`bamos/ubuntu-opencv-dlib-torch   ubuntu_14.04-opencv_2.4.11-dlib_19.0-torch_2016.07.12   3fc9716bd22e        3 years ago         1.46GB`

Looks like it is pulling the image from library and It is quite outdated. Please advise.

**Comment by jaharkes** [comment]
That was the 'current' system when openface was originally implemented and trained. I'm not sure if torch has changed any of it's internal datastructures or anything so using that ancient image reproduces the original build as closely as possible.
This is sort of the point of Docker isn't it?
If you can successfully build with more up-to-date dependencies then by all means, report your success and possible a pull request to update the Dockerfile.

btw. I believe this is the dockerfile for that old ubuntu14.04+opencv+dlib+torch image, https://github.com/cmusatyalab/openface/blob/master/opencv-dlib-torch.Dockerfile

Because Docker caches layers, they could probably be combined into a single file.
