### ISSUE TITLE
Move Lua subprocess into a server

### ISSUE THREAD

**Issue by bamos** [cmusatyalab/openface#4]
+ https://github.com/cmusatyalab/openface/blob/master/openface/openface_server.lua
+ Hacky workaround to #1 that runs a server taking an input filename on stdin and outputting the model's representation on stdout.
+ Improve it to use a communication library, possibly over HTTP with a framework like https://luvit.io/, or with json/protobuf.
+ Need to solve Python OpenCV RGB in numpy array -> Lua Torch RGB Tensor.

**Comment by soumith** [comment]
https://github.com/clementfarabet/async is excellent and integrates well with the torch ecosystem (it also does not have any external dependencies to install, so very nice that way).

- wrt #1 the most painless thing to do is handle all the torch API over network. Compared to your network runtime of 80ms-ish, this will be minute overhead (1-5ms?) 
- OpenCV RGB numpy array -> Lua Torch RGB Tensor is pretty doable. You dont need any mem-copy, just get the size/stride/data-pointer from OpenCV and create a tensor with those.

**Comment by bamos** [comment]
Great references, thanks @soumith!

**Comment by TylerL-uxai** [comment]
Hey folks, checking in to see if I can help with this even though I'm pretty new to lua. I see you're using openface_server instead of facenet. Is that what needs updating? I'm assuming your goal is to run a server asynchronously.

https://github.com/cmusatyalab/openface/blob/master/openface/openface_server.lua
