### ISSUE TITLE
Web demo: Reduce data transfers

### ISSUE THREAD

**Issue by bamos** [cmusatyalab/openface#47]
Suggested by @anguoyang:

Such as:

+ [ ] Compression
+ [ ] Doing detection in the browser and only sending cropped faces
+ [ ] Only sending bounding boxes and labels back from the server to the browser

**Comment by cowbjt** [comment]
Hi @bamos,

I forked the project and did the following things.
1. Save the trained data in database(SQLite).
2. Take off the "face representation" and "trained face image" from the communication data between server and client.
(doing send the url of trained face to client now)
3. Sync trained face with client when new connection established.
(because of taking off those 2 field, the synchronization is quite fast)

But I also wrote a wrapper of openface for studying the usage the openface.
I am not sure if that fits with the original structure design.

Here is the forked repository:
https://github.com/cowbjt/openface
and modified code is in demo-web-stand-alone branch.

If anything I can help, please let me know.

**Comment by bamos** [comment]
Hi @cowbjt - thank you for letting us know about your modifications.
[This comparison](https://github.com/cmusatyalab/openface/compare/master...cowbjt:demo-web-stand-alone) shows you've added about 1500 lines of code.
Persisting the faces is also relevant to #19.

I'm excited to look through your modifications, but probably won't be
able to until next week.

-Brandon.

**Comment by bamos** [comment]
Hi @cowbjt - thanks again for letting us know about your modifications. I've added a link to your fork to our website at http://cmusatyalab.github.io/openface/demo-1-web/.

-Brandon.

**Comment by chopzanaka** [comment]
Hi @bamos I can not run image cowbjt . (Local : Disconnect)
