### ISSUE TITLE
How can i get model?

### ISSUE THREAD

**Issue by neuralix** [cmusatyalab/openface#56]
Thank you for offering good code.

I have done training, and get files like below.

in {Openface_Root}/training/work/21: 
    classes.t7, model_#.t7, optimState_#.t7, opts.t7, test.log, train.log

How can i get corresponding files(:{celeb-classifier.nn4.v1.pkl,  nn4.v1.t7, shape_predictor_68_face_landmarks.dat}) from files above?

**Comment by sschnug** [comment]
Your "training" is only responsible for training the model (the neural network). So your training replaces "nn4.v1.t7".

The other files are not generated during training:

- shape_predictor_68_face_landmarks.dat is trained data for landmark-detection in faces commonly used in dlib
- celeb-classifier.nn4.v1.pkl seems to be a pickled file describing a trained classifier on some images -> you can generate your own classifier (read documentation). A training of a classifier processes the feature-vectors of the images, therefore you habe to use your trained network to generate these and then build your classifier!

**Comment by bamos** [comment]
Thanks @sschnug for the great references!

@neuralix  - the trained DNN model indeed replaces `nn4.v1.t7` if that's what you want to do. Make sure you understand the differences between training a DNN model and a classification model, which the documentation describes:

+ http://cmusatyalab.github.io/openface/demo-3-classifier/
+ http://cmusatyalab.github.io/openface/training-new-models/

I'm closing this since the issue tracker is for development discussions and tracking bugs, but please come to the Gitter chat or mailing list (linked in the README) if this wasn't clear.
