### ISSUE TITLE
Web demo: Bug when labeling with radio buttons

### ISSUE THREAD

**Issue by bamos** [cmusatyalab/openface#82]
From @SyRenity in [this](https://groups.google.com/forum/#!topic/cmu-openface/BakNUG5Lr1w) mailing list thread:

---

> 1. Install the latest docker version:
>    docker pull bamos/openface
> 2. Launch the docker as bash (regular launch didn't work for me, complaining it can't find th):
>    docker run -t -i -p 8000:8000 -p 9000:9000 bamos/openface /bin/bash
> 3. Click train to start training
> 4. Stop training after 7-10 images
> 5. Add a name
> 6. Click in trained faces list on the added name radio button to assign name to face
> 7. Demo crashes with:
>    
>    ```
>    2016-01-21 20:51:46+0000 [-] /usr/local/lib/python2.7/dist-packages/sklearn/cross_validation.py:417: exceptions.Warning: The least populated class in y has only 1 members, which is too few. The minimum number of labels for any class cannot be less than n_folds=5.
>    2016-01-21 20:51:46+0000 [OpenFaceServerProtocol,0,192.168.253.221] Unhandled Error
>    
>    exceptions.ValueError: The number of classes has to be greater than one; got 1
>    ```
> 
> By the way, if I follow the demo youtube video usage flow (first creating a name then training), it works fine.

**Comment by abduallahadel** [comment]
I'm also facing the same issue .... 
Any hints on how to solve ?

**Comment by abduallahadel** [comment]
@bamos any ideas ?

**Comment by giaosucan** [comment]
I got this problem as well

**Comment by calidoso** [comment]
Hello ,
This is because SVM by default is multiclase and as the error says you are trying to train only one class.
See official documentation. http://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html

In a nutshell you try to train a model with only one person.
If for some reason, so you need, I can think of a dirty trick.

Creates 2 folders one with data of the person to identify and another with data that you will call unknown.

I apologize for my English, I do not speak it natively.
