### ISSUE TITLE
OpenFace: `openface_server.lua` subprocess has died.

### ISSUE THREAD

**Issue by ZoranPavlovic** [cmusatyalab/openface#84]
After trying to follow the docker instructions from http://cmusatyalab.github.io/openface/setup/ I get an error on the first demo file being run.

Commands run:
./demos/compare.py images/examples/{lennon*,clapton*}

Output:

Traceback (most recent call last):
  File "./demos/compare.py", line 101, in <module>
    d = getRep(img1) - getRep(img2)
  File "./demos/compare.py", line 92, in getRep
    rep = net.forward(alignedFace)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 149, in forward
    rep = self.forwardPath(t)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 102, in forwardPath
    """.format(self.cmd, self.p.stdout.read(), self.p.stderr.read()))
Exception: 

OpenFace: `openface_server.lua` subprocess has died.
Is the Torch command `th` on your PATH? Check with `which th`.

Diagnostic information:

cmd: ['/usr/bin/env', 'th', '/usr/local/lib/python2.7/dist-packages/openface/openface_server.lua', '-model', '/root/src/openface/demos/../models/openface/nn4.small2.v1.t7', '-imgDim', '96']

============

stdout: 

============

stderr:

**Comment by bamos** [comment]
Hi @ZoranPavlovic - are you running this on a non-64-bit machine? If so, this is related to #42. If you are on a 64-bit machine, can you try running [util/profile-network.lua](https://github.com/cmusatyalab/openface/blob/master/util/profile-network.lua) to see if it works?

**Comment by ZoranPavlovic** [comment]
Hi @bamos - This is on a 64bit machine, Ubuntu 15.04.

root@980433e5fc99:/# ./root/src/openface/util/profile-network.lua
Illegal instruction (core dumped)

**Comment by bamos** [comment]
Hi @ZoranPavlovic - you need to build the Docker container from scratch to resolve this. See this portion of our [faq](http://cmusatyalab.github.io/openface/faq) for more details. Can you try this and let me know if it fixes the issue?

> ### I'm getting an illegal instruction error in the pre-built Docker container.
This is unfortunately a result of building the Docker container on one machine that compiles software with non-standard CPU flags and creates illegal instructions on architectures that don't support the additional CPU features. Using the binaries from the pre-built container on a CPU that doesn't support these features results in the illegal instruction error. We try to prevent these as much as possible by building the images inside of a Docker machine. If you are still having these issues, please fall back to building the image from scratch instead of pulling from Docker Hub. You'll need to build the opencv-dlib-torch Dockerfile, change the FROM part of the OpenFace Dockerfile to your version, then build the OpenFace Dockerfile.

**Comment by anthonyyuan** [comment]
hi I also meet the same problem ! I use java to get this python interface. I use Mac book os 10.10!!!!!!!!!!!!Commands run:
./demos/compare.py images/examples/{lennon,clapton}

Output:

Traceback (most recent call last):
File "./demos/compare.py", line 101, in 
d = getRep(img1) - getRep(img2)
File "./demos/compare.py", line 92, in getRep
rep = net.forward(alignedFace)
File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 149, in forward
rep = self.forwardPath(t)
File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 102, in forwardPath
""".format(self.cmd, self.p.stdout.read(), self.p.stderr.read()))
Exception:

OpenFace: openface_server.lua subprocess has died.
Is the Torch command th on your PATH? Check with which th.

Diagnostic information:

cmd: ['/usr/bin/env', 'th', '/usr/local/lib/python2.7/dist-packages/openface/openface_server.lua', '-model', '/root/src/openface/demos/../models/openface/nn4.small2.v1.t7', '-imgDim', '96']

**Comment by bamos** [comment]
Hi @anthonyyuan - can you try running `util/profile-network.lua` to see if it works?

-Brandon.

**Comment by pinguo-luhaofang** [comment]
Hi @bamos, I use my 64-bit machine running "util/profile-network.lua",
and the output is "/usr/bin/env: th: can't find the file or dictionary", Do I missed something?

**Comment by bamos** [comment]
Hi @pinguo-luhaofang - have you installed Torch and is it on your PATH?

I'm closing this thread since the issue tracker is for development discussions and specific bug tracking. Let's move further setup discussions to our mailing list at https://groups.google.com/forum/#!forum/cmu-openface.

-Brandon.
