### ISSUE TITLE
training the DNN model

### ISSUE THREAD

**Issue by sharmasaravanan** [cmusatyalab/openface#96]
what are the changes has to be done in training/opts.lua  [here](http://cmusatyalab.github.io/openface/training-new-models/) ??

**Comment by bamos** [comment]
Hi, thanks for filing an issue with us. However, I am closing it because the issue tracker is for development discussions and specific bug tracking.
Please re-post this to [our mailing list](https://groups.google.com/forum/#!forum/cmu-openface) and review our [contribution guidelines](https://github.com/cmusatyalab/openface/blob/master/CONTRIBUTING.md).

-Brandon.
