### ISSUE TITLE
triplet selection

### ISSUE THREAD

**Issue by pinguo-luhaofang** [cmusatyalab/openface#97]
### Context of the issue.
Hi, I want to train a vgg network by tripletloss , but loss is NOT convergent. Has anyone face the same condition? I selected the triplet in offline way. Paper says :
![image](https://cloud.githubusercontent.com/assets/13896922/13208035/ec9c0d90-d94f-11e5-967c-afdeab0973ed.png)
so I wonder if it could be used.

**Comment by bamos** [comment]
Hi @pinguo-luhaofang, thanks for filing an issue with us. However, I am closing it because the issue tracker is for development discussions and specific bug tracking.
Please re-post this to [our mailing list](https://groups.google.com/forum/#!forum/cmu-openface) and review our [contribution guidelines](https://github.com/cmusatyalab/openface/blob/master/CONTRIBUTING.md).

-Brandon.
